version: '3.8'

services:
  streamlit:
    build: .
    container_name: dreamfactory-portal
    ports:
      - "8501:8501"
    volumes:
      - ~/.streamlit:/app/.streamlit
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
    restart: unless-stopped 